apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-app-credentials
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: api-app-credentials
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: lab-eks/external-secrets/app
        property: username
