apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev
images:
  - name: unedotamps/api-app
    newTag: sha-39c90d17836b46c3c872f2c6ae02708fb8743ed0

replicas:
  - name: api-app
    count: 3
