apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: dev
images:
  - name: unedotamps/api-app
    newTag: sha-b2d1bb828aa33935d58c31125717ff2f05cf8b62
replicas:
  - name: api-app
    count: 3
