apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev
images:
  - name: unedotamps/api-app
    newTag: sha-945cc7b76475936b7c94a6762d6057c832ad7749

replicas:
  - name: api-app
    count: 3
